### PR TITLE
Fixes bug in PathFactoids that can cause test failures to be ignored.

### LINKED ISSUE #46: PathFactoids potentially ignores test failures
`PathFactoids` doesn't use the Specs2 API correctly. This can cause test failures to be ignored in the case where there are other expectations following the path factoid.

Instead of extending `ThrownExpectations` `PathFactoids` should extend `MustThrownExpectations`.

### PR DESCRIPTION
**Pull request by stephanh**
`checkEquality`in `PathFactoids` uses `must` to create a Specs2
`Result`. For this to create a failure when using `ThrownExpecations`
`PathFactoids` needs to extend `MustThrownExpecations`. This affects all
the `records` functions.

This fixes #46.

### CODE REVIEW

File: core/src/test/scala/au/com/cba/omnia/thermometer/fact/PathFactSpec.scala [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+//
+//   Unless required by applicable law or agreed to in writing, software
+//   distributed under the License is distributed on an "AS IS" BASIS,
+//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+//   See the License for the specific language governing permissions and
+//   limitations under the License.
+
+package au.com.cba.omnia.thermometer.fact
+
+import java.nio.file.{Files, Paths}
```
Comment (vineethvarghese) [inline core/src/test/scala/au/com/cba/omnia/thermometer/fact/PathFactSpec.scala]: Why do we need these imports?

File: core/src/test/scala/au/com/cba/omnia/thermometer/fact/PathFactSpec.scala [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+
+import au.com.cba.omnia.thermometer.test.Spec
+
```
Comment (vineethvarghese) [inline core/src/test/scala/au/com/cba/omnia/thermometer/fact/PathFactSpec.scala]: Shouldn't these 3 imports come together?

File: core/src/test/scala/au/com/cba/omnia/thermometer/fact/PathFactSpec.scala [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+import au.com.cba.omnia.thermometer.core.ThermometerSpec
+import au.com.cba.omnia.thermometer.fact.PathFactoids._
+
+object PathFactoidsSpec extends ThermometerSpec { def is = s2"""
+PathFactoids
+============
+
+  `checkEquality`` correctly handles test failures where multiple expectations are checked
```
Comment (vineethvarghese) [inline core/src/test/scala/au/com/cba/omnia/thermometer/fact/PathFactSpec.scala]: What does the `` in `checkEquality``do?

File: core/src/test/scala/au/com/cba/omnia/thermometer/fact/PathFactSpec.scala (hunk 1 above)
Comment (stephanh) [inline core/src/test/scala/au/com/cba/omnia/thermometer/fact/PathFactSpec.scala]: They were leftovers. I removed them.

File: core/src/test/scala/au/com/cba/omnia/thermometer/fact/PathFactSpec.scala (hunk 2 above)
Comment (stephanh) [inline core/src/test/scala/au/com/cba/omnia/thermometer/fact/PathFactSpec.scala]: Good point.

**Comment by vineethvarghese** [comment]
A few minor comments but otherwise :+1:

File: core/src/test/scala/au/com/cba/omnia/thermometer/fact/PathFactSpec.scala (hunk 3 above)
Comment (stephanh) [inline core/src/test/scala/au/com/cba/omnia/thermometer/fact/PathFactSpec.scala]: Nothing, just a typo.
